export const RETURN_CODE = {
  /* Global Error Code */
  EH001: '잘못된 요청입니다.',
  EH002: '요청한 페이지 URL이 없습니다.',
  EH003: 'Request Header 정보가 올바르지 않습니다.',
  EH004: 'Request Body 데이터가 없습니다.',
  EH005: 'Request Parameter 데이터가 없습니다.',
  EA001: '로그인 정보가 없습니다.',
  EA002: '수행할 권한이 없습니다.',
  EV001: '입력한 정보를 찾을 수 없거나 입력한 정보와 서버가 필요한 정보와 매칭이 되지 않습니다.',
  EG001: 'Null Point Exception 발생',
  EG002: 'I/O Exception',
  EG003: 'Json 파싱이 실패했습니다.',
  EG999: '내부 서버 오류',

  /* 시스템 공통 */
  EP000: '권한이 충분치 않습니다.',
  EP001: '동영상 파일은 지원하지 않습니다.',
  EP002: '이미지 파일 개수 제한을 초과하였습니다.',
  EP003: 'depth를 다시 설정해주세요.',
  EP004: '해당 파일 타입은 지원하지 않습니다.',
  EP005: '위치 좌표가 필요합니다.',

  /* 인증 및 사용자 정책 에러 코드 */
  EP100: '로그인 토큰 정보가 없습니다.',
  EP101: '비밀번호가 일치하지 않습니다.',
  EP102: '이미 등록된 ID입니다.',
  EP103: '휴면 회원입니다.',
  EP104: '휴면 회원이 아닙니다.',
  EP105: '유저명이 일치하지 않습니다.',
  EP106: '이미 가입이 되어있는 번호입니다.',
  EP107: '이미 가입이 되어있는 이메일입니다.',
  EP108: '휴대폰 인증번호의 인증유효시간이 지났습니다. 다시 인증해주세요.',
  EP109: '이메일 인증번호의 인증 유효기간이 지났습니다. 다시 인증해주세요.',
  EP110: '인증을 먼저 진행해주세요.',
  EP111: 'SMS 인증 번호 재발급 회수가 제한을 넘었습니다.',
  EP112: '지원하지 않는 UserPinCodeType입니다.',
  EP113: '이메일 인증번호 발급을 먼저 진행해주세요.',
  EP114: 'SMS 인증번호 발급을 먼저 진행해주세요.',
  EP115: '인증번호가 일치하지 않습니다.',
  EP116: 'Refresh Token이 만료되었습니다.',
  EP117: '가입되지 않은 아이디입니다.',
  EP118: '회원 심사가 완료되지 않았습니다.',
  EP119: '회원 심사 결정을 할 수 없습니다. 심사 대기 상태가 아닙니다.',
  EP120: '주민 인증이 되지 않은 사용자입니다.',
  EP121: '배심원이 될 수 없습니다.',
  EP122: '주민 인증키 값이 유효하지 않습니다.',
  EP123: '주민 인증키가 만료되었습니다.',
  EP124: '탈퇴한 회원입니다.',
  EP125: '회원 심사가 반려되었습니다.',
  EP126: '블랙된 회원입니다.',
  EP127: '이메일은 빈값으로 변경할 수 없습니다.',

  /* 로컬박스 정책 에러 코드 */
  EP200: '활동하는 로컬박스가 없습니다.',
  EP201: '일반 크리에이터만 동네 설정을 변경할 수 있습니다.',

  /* 사이니지 정책 에러 코드 */
  EP300: '이미 등록되어 있는 사이니지 디바이스 명입니다.',
  EP301: '해당 사이니지는 인증되지 않았습니다.',
  EP302: '해당 사이니지는 이미 그룹에 속해 있습니다.',
  EP303: '해당 사이니지 시리얼 번호는 이미 사용중에 있습니다.',
  EP304: '사이니지 모델명이 잘못되었습니다.',
  EP305: '해당 사이니지 그룹은 인증되지 않았습니다.',
  EP306: '사이니지 프로젝트와 사이니지 그룹의 화면 비율과 다릅니다.',
  EP307: '이미 등록되어 있는 사이니지 그룹 명입니다.',
  EP308: '재생할 수 없는 사이니지 프로젝트 입니다.',
  EP309: '심사 완료된 사이니지 디바이스 입니다.',
  EP310: '이미 심사 진행중인 사이니지가 있습니다.',
  EP311: '사이니지 인증을 진행해주세요.',
  EP312: '이미 있는 사이니지 프로젝트명입니다.',
  EP313: '사이니지가 그룹에 소속되지 않았습니다.',
  EP314: '이미 해당 시간에 사이니지가 예약되어 있습니다.',
  EP315: '해당 프로젝트는 현재 재생중입니다.',
  EP316: '기본 프로젝트로 설정되어 있습니다. 기본 프로젝트 해제를 먼저 진행해주세요.',
  EP317: '사이니지가 그룹이 인증되어 있습니다.',
  EP318: '사이니지 디바이스 비율타입이 올바르지 않습니다.',
  EP319: '모든 디바이스 신청이 아직 승인되지 않았습니다.',
  EP320: '심사 중인 디바이스가 있을 경우에는 디바이스를 신청할 수 없습니다.',
  EP321: '사이니지 그룹 심사 정보를 수정할 수 있는 상태가 아닙니다.',
  EP322: '사이니지 그룹 정보를 수정할 수 있는 상태가 아닙니다.',
  EP323: '사이니지 프로젝트와 사이니지 그룹의 화면 비율과 다릅니다.',
  EP324: '사이니지 예약을 할 수 없는 시간입니다.',

  /* 콘텐츠 정책 에러 코드 */
  EP400: '콘텐츠 디스플레이 타입은 수정할 수 없습니다.',
  EP401: '심사 접수된 광고 콘텐츠는 수정할 수 없습니다.',
  EP402: '해당 동네소식 콘텐츠가 설정한 내 동네 컨텐츠가 아닙니다.',
  EP403: '동네소식 콘텐츠 포스팅 조건을 충족되지 않았습니다.',
  EP404: '사이니지 콘텐츠가 아닙니다.',
  EP405: '사이니지 콘텐츠 화면 비율타입이 올바르지 않습니다.',
  EP406: '사이니지 콘텐츠는 노출 설정을 할 수 없습니다.',
  EP407: '노출영역을 설정하는 콘텐츠가 아닙니다.',
  EP408: '동네소식 콘텐츠만 지역성 신고를 할 수 있습니다.',
  EP409: '블라인드 취소 요청한 콘텐츠는 수정할 수 없습니다.',
  EP410: '신고된 콘텐츠 입니다.',
  EP411: '지역성 신고된 콘텐츠입니다.',
  EP412: '사이니지 콘텐츠는 북마크 설정을 할 수 없습니다.',
  EP413: '해당 콘텐츠는 지역성 신고를 할 수 없습니다.',
  EP414: '해당 콘텐츠는 콘텐츠 노출 영역이 잘 되어 있어서 신고를 할 수 없습니다.',
  EP415: '사이니지 콘텐츠는 신고할 수 없습니다.',
  EP416: '해당 콘텐츠 타입은 지원하지 않습니다.',
  EP417: '심사 미승인 되었기 때문에 콘텐츠를 수정하고 심사를 요청해야 합니다.',
  EP418: '콘텐츠가 포스팅 되어 노출되어 있습니다.',
  EP419: '포스팅 이후 7일 이후에 신청해주세요.',
  EP420: '콘텐츠가 심사 진행중입니다.',
  EP421: '광고 콘텐츠는 댓글을 등록할 수 없습니다.',
  EP422: '콘텐츠 해시태그는 5개를 초과하여 등록할 수 없습니다.',
  EP423: '해당 콘텐츠 타입은 지원하지 않습니다.',
  EP424: '콘텐츠 title과 사이니지 콘텐츠 title 이 다릅니다.',
  EP425: '일반 회원은 콘텐츠를 등록할 수 없습니다.',
  EP426: '임시 콘텐츠를 더 이상 저장할 수 없습니다.',
  EP427: '모바일 콘텐츠가 아닙니다.',
  EP428: '동네소식 콘텐츠는 사이니지 콘텐츠 추가를 할 수 없습니다.',

  /* 콘텐츠 댓글 정책 에러 코드 */
  EP500: '신고된 댓글입니다',

  /* 사업자 정책 에러 코드 */
  EP600: '이미 가입된 사업자등록번호 입니다.',
  EP601: 'licenseImage는 필수입니다.',
  EP602: '잘못된 사업자 정보입니다.',

  /* 결제 관련 에러 코드 */
  EP700: '결제가 진행되어야 합니다.',
  EP701: '결제 정보를 수정해주세요.',
  EP702: '이미 결제가 되었거나 진행 중입니다.',
  EP703: '구독 서비스를 먼저 해지하고 결제 정보를 삭제해주세요.',
  EP704: '기존 결제 정보를 삭제하고 등록해주세요.',

  /* 기관 정책 에러 코드 */
  EP800: '공유할 기관 정보가 없습니다.',
  EP801: '해당 기관에는 이미 가입되어 있는 크리에이터가 있습니다.',
  EP802: '기관에 의해 차단이 되었습니다.',
  EP803: '기관에 이미 인증된 상태입니다.',
  EP804: '이미 등록한 장소입니다.',
  EP805: '이미 등록한 장소입니다.',
  EP806: '해당 기관은 이미 가입되어 있습니다.',
  EP807: '해당 기관에 이미 가입 신청을 하셨습니다.',
  EP808: '심사를 진행할 수 없는 상태입니다.',
  EP809: '해당 기관에 QR 인증할 수 없습니다.',

  /* 기타 관련 에러 코드 */
  EP900: '공지사항 파일 업로드 개수는 최대 10개를 초과하여 등록할 수 없습니다.',
  EP901: '블랙된 회원은 QR 주민인증 기록을 삭제할 수 없습니다.',

  /* 등록 에러 코드 */
  EI001: 'Content 등록 실패',
  EI002: 'Content Complain Process 등록 실패',
  EI003: 'Content Locality Complain Process 등록 실패',
  EI004: 'Localbox 등록 실패',
  EI005: 'Content File 등록 실패',
  EI006: 'Area Polygon Info 등록 실패',
  EI007: 'Content Approval 등록 실패',
  EI008: 'Content Search Keyword 등록 실패',
  EI009: 'Content Reply 등록 실패',
  EI010: 'Content Reply Complain process 등록 실패',
  EI011: 'Signage device 등록 실패',
  EI012: 'Signage device Approval 등록 실패',
  EI013: 'Signage Device Spec 등록 실패',
  EI014: 'Signage Group Approval 등록 실패',
  EI015: 'Signage Group 등록 실패',
  EI016: 'Signage Project 등록 실패',
  EI017: 'Payment Info 등록 실패',
  EI018: 'User 등록 실패',
  EI019: 'User Reg Approval 등록 실패',
  EI020: 'User Pin Code 등록 실패',
  EI021: 'Localbox Organization Mapping 등록 실패',
  EI022: 'Notification 등록 실패',
  EI023: 'Organization Hierarchy 등록 실패',
  EI024: 'QR Image 등록 실패',
  EI025: 'QR Jumin Certification 등록 실패',
  EI026: 'Organization Reg Process 등록 실패',
  EI027: 'Fcm Token 등록 실패',
  EI028: 'Popup 등록 실패',
  EI029: 'Banner 등록 실패',
  EI030: 'Content Count Info 등록 실패',
  EI031: 'Content Reply Count Info 등록 실패',
  EI032: 'Notice 등록 실패',
  EI033: 'Signage Reservation 등록 실패',
  EI034: 'ContentTemp 등록 실패',
  EI035: 'SignageGroupApprovalFile 등록 실패',
  EI036: 'Content Signage 등록 실패',

  /* 조회 에러 코드 */
  ES001: 'Content 조회 실패',
  ES002: 'Content Complain Process 조회 실패',
  ES003: 'Content Locality Complain Process 조회 실패',
  ES004: 'Localbox 조회 실패',
  ES005: 'Content File 조회 실패',
  ES006: 'Area Polygon Info 조회 실패',
  ES007: 'Content Approve 조회 실패',
  ES008: 'Recent Serach Keyword 조회 실패',
  ES009: 'Content reply 조회 실패',
  ES010: 'Content Reply Complain Process 조회 실패',
  ES011: 'Signage Device 조회 실패',
  ES012: 'Signage Device Approval 조회 실패',
  ES013: 'Signage Device Spec 조회 실패',
  ES014: 'Signage Group Approval 조회 실패',
  ES015: 'Signage Group 조회 실패',
  ES016: 'Signage Project 조회 실패',
  ES017: 'Payment Info 조회 실패',
  ES018: '입력한 이메일 본인정보가 일치하지 않습니다.',
  ES019: 'User Reg Approval 조회 실패',
  ES020: 'User Pin Code 조회 실패',
  ES021: 'Localbox Organization Mapping 조회 실패',
  ES022: 'Notification 조회 실패',
  ES023: 'Organization Hierarchy 조회 실패',
  ES024: 'Qr Image Data 조회 실패',
  ES025: 'Qr Jumin Certification 조회 실패',
  ES026: 'Organization Reg Process 조회 실패',
  ES027: 'Fcm Token 조회 실패',
  ES028: 'Popup 조회 실패',
  ES029: 'Banner 조회 실패',
  ES030: 'Content Count Info 조회 실패',
  ES031: 'Content Reply Count Info 조회 실패',
  ES032: 'Notice 조회 실패',
  ES033: 'Signage Reservation 조회 실패',
  ES034: 'ContentTemp 조회 실패',
  ES035: 'SignageGroupApprovalFile 조회 실패',
  ES036: 'Content Signage 조회 실패',

  /* 수정 에러 코드 */
  EU001: 'Content 수정 실패',
  EU002: 'Content Complain Process 수정 실패',
  EU003: 'Contents Locality Complain Process 수정 실패',
  EU004: 'Localbox 수정 실패',
  EU005: 'Content File 수정 실패',
  EU006: 'Area Polygon Info 수정 실패',
  EU007: 'Content Approval 수정 실패',
  EU008: 'Recent Search Keyword 수정 실패',
  EU009: 'Content Reply 수정 실패',
  EU010: 'Content Reply Complain Process 수정 실패',
  EU011: 'Signage Device 수정 실패',
  EU012: 'Signage Device Approval 수정 실패',
  EU013: 'Signage Device Spec 수정 실패',
  EU014: 'Signage Group Approval 수정 실패',
  EU015: 'Signage Group 수정 실패',
  EU016: 'Signage Project 수정 실패',
  EU017: 'Payment Info 수정 실패',
  EU018: 'User 수정 실패',
  EU019: 'User Reg Approval 수정 실패',
  EU020: 'User Pin Code 수정 실패',
  EU021: 'Localbox Organization Mapping 수정 실패',
  EU022: 'Notification 수정 실패',
  EU023: 'Organization Hierarchy 수정 실패',
  EU024: 'Qr Image Data 수정 실패',
  EU025: 'Qr Jumin Certification 수정 실패',
  EU026: 'Organization Reg Process 수정 실패',
  EU027: 'Fcm Token 수정 실패',
  EU028: 'Popup 수정 실패',
  EU029: 'Banner 수정 실패',
  EU030: 'Content Count Info 수정 실패',
  EU031: 'Content Reply Count Info 수정 실패',
  EU032: 'Notice 수정 실패',
  EU033: 'Signage Reservation 수정 실패',
  EU034: 'ContentTemp 수정 실패',
  EU035: 'SignageGroupApprovalFile 수정 실패',
  EU036: 'Content Signage 수정 실패',

  /* 삭제 에러 코드 */
  ED001: 'Content 삭제 실패',
  ED002: 'ContentComplainProcess 삭제 실패',
  ED003: 'ContentLocalityComplainProcess 삭제 실패',
  ED004: 'Localbox 삭제 실패',
  ED005: 'Content File 삭제 실패',
  ED006: 'Area Polygon Info 삭제 실패',
  ED007: 'Content Approval 삭제 실패',
  ED008: 'Recent Search Keyword 삭제 실패',
  ED009: 'Content Reply 삭제 실패',
  ED010: 'Content Reply Complain Process 삭제 실패',
  ED011: 'Signage Device 삭제 실패',
  ED012: 'Signage Device Approval 삭제 실패',
  ED013: 'Signage Device Spec 삭제 실패',
  ED014: 'Signage Group Approval 삭제 실패',
  ED015: 'Signage Group 삭제 실패',
  ED016: 'Signage Project 삭제 실패',
  ED017: 'Payment Info 삭제 실패',
  ED018: 'User 삭제 실패',
  ED019: 'User Reg Approval 삭제 실패',
  ED020: 'User Pin Code 삭제 실패',
  ED021: 'Localbox Organization Mapping 삭제 실패',
  ED022: 'Notification 삭제 실패',
  ED023: 'Organization Hierarchy 삭제 실패',
  ED024: 'Qr Image Data 삭제 실패',
  ED025: 'Qr Jumin Certification 삭제 실패',
  ED026: 'Organization Reg Process 삭제 실패',
  ED027: 'Fcm Token 삭제 실패',
  ED028: 'Popup 삭제 실패',
  ED029: 'Banner 삭제 실패',
  ED030: 'Content Count Info 삭제 실패',
  ED031: 'Content Reply Count Info 삭제 실패',
  ED032: 'Notice 삭제 실패',
  ED033: 'Signage Reservation 삭제 실패',
  ED034: 'ContentTemp 삭제 실패',
  ED035: 'SignageGroupApprovalFile 삭제 실패',
  ED036: 'Content Signage 삭제 실패',
};
