name: Auto PR for ondaji constants changes

on:
  push:
    branches:
      - main
    paths:
      - "src/constants/ondaji/**"

permissions:
  contents: write

jobs:
  auto-pr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # 전체 커밋 이력을 가져옵니다.
          token: ${{ secrets.ACCESS_TOKEN }} # PAT 사용

      - name: Set up Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Add ondaji-constants remote if not exists
        run: |
          if ! git remote | grep -q ondaji-constants; then
            git remote add ondaji-constants https://x-access-token:${{ secrets.ACCESS_TOKEN }}@github.com/altsoft5472344/ondaji_4gen_front_constants.git
          fi

      - name: Check for changes in ondaji-constants
        id: check_changes
        run: |
          # 이전 commit과 현재 commit 간의 변경사항을 확인합니다.
          if git diff --name-only ${{ github.event.before }} ${{ github.event.after }} | grep -q '^src/constants/ondaji/'; then
            echo "Detected file changes in src/constants/ondaji."
            echo "changes=true" >> $GITHUB_OUTPUT
          else
            echo "No file changes in src/constants/ondaji."
            echo "changes=false" >> $GITHUB_OUTPUT
          fi

      - name: Create branch and push subtree if changes exist
        if: steps.check_changes.outputs.changes == 'true'
        run: |
          # 고유한 브랜치 이름 생성 (예: auto-ondaji-constants-타임스탬프)
          BRANCH="auto-ondaji-constants-$(date +%s)"
          echo "Creating branch $BRANCH"
          git checkout -b $BRANCH
          # --squash 옵션을 사용해 커밋 이력을 단순화합니다.
          git subtree push --prefix=src/constants/ondaji ondaji-constants $BRANCH

      - name: Install GitHub CLI
        if: steps.check_changes.outputs.changes == 'true'
        run: sudo apt-get update && sudo apt-get install -y gh

      - name: Create Pull Request using GitHub CLI
        if: steps.check_changes.outputs.changes == 'true'
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        run: |
          BRANCH=$(git rev-parse --abbrev-ref HEAD)
          echo "현재 브랜치: $BRANCH"
          git fetch origin main
          CHANGED_FILES=$(git diff origin/main..$BRANCH --name-only | grep '^src/constants/ondaji/')
          if [ -z "$CHANGED_FILES" ]; then
            echo "main과 $BRANCH 간에 src/constants/ondaji 내 변경된 파일이 없음."
            exit 0
          else
            echo "$CHANGED_FILES"
            COMMIT_MESSAGE="${{ github.event.head_commit.message }}"
            COMMIT_TITLE=$(echo "$COMMIT_MESSAGE" | head -n 1 | sed -E 's/[[:space:]]*\(\#[0-9]+\)//g')
            COMMIT_URL="${{ github.event.head_commit.url }}"
            COMMIT_AUTHOR="${{ github.event.head_commit.author.name }}"
            BODY="커밋 메시지: ${COMMIT_TITLE}
            커밋 URL: ${COMMIT_URL}
            커밋 작성자: @${COMMIT_AUTHOR}"
            gh pr create --title "${COMMIT_TITLE}" \
                        --body "$BODY" \
                        --base main --head $BRANCH
          fi
